name: Deploy React Frontend

on:
  push:
    branches:
      - [main ,master]  # Jab bhi main branch pe push hoga, workflow trigger hoga

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} -t react-app .
          docker tag react-app ${{ secrets.DOCKER_USERNAME }}/react-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-app:latest
            docker stop react-app || true
            docker rm react-app || true
            docker run -d -p 80:80 --name react-app ${{ secrets.DOCKER_USERNAME }}/react-app:latest
