name: Deploy React Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_DEV_URL }} -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

      - name: Test SSH Connection to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: echo "✅ SSH connection successful."

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-app:latest

            docker stop react-app || true
            docker rm react-app || true

            docker image prune -f

            docker run -d \
              -p 80:80 \
              --name react-app \
              --restart always \
              -e REACT_APP_API_URL=${{ secrets.REACT_APP_API_DEV_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/react-app:latest
